### ISSUE TITLE
"put" arguments must be integers

### ISSUE THREAD

**Issue by itsayellow** [quentinsf/qhue#11]
I'm not sure if this is something to be fixed in the code, but it might be worth mentioning in the docs:

If you give a number to the Hue Bridge that is not an integer, it will likely ignore it.  And anything resulting from simple math will not be an integer, even if it has no fractional component.

For instance, PUTting the following to the state of my light does nothing:
{"ct":400.0}
However, this correctly changes the state of the light:
{"ct":400}
(verified with the clip debugger)

The same thing is at play in qhue, I believe the json module is just using str() or something like it to make a number into a string.  This makes doing using a math result complicated, as all results must be cast to integers before delivering to qhue.  (Simple arithmetic always seems to result in a float)

For example the following in qhue does nothing:
`lights[1].state(ct=1e6/2000)`
However, this works correctly
`lights[1].state(ct=int(1e6/2000))`

i.e.
```
>>> 1e6/2000
500.0
>>> int(1e6/2000)
500
```

**Comment by quentinsf** [comment]
Thanks Matthew  - have added something about this to the README.

Much appreciated,
Quentin
