### ISSUE TITLE
URL-like paths in Qhue

### ISSUE THREAD

**Issue by quentinsf** [quentinsf/qhue#12]
Dear Qhue contributors - 

I had an idea for a small change to [Qhue](https://github.com/quentinsf/qhue), and thought I'd bounce it off you to see if you thought it was clever, or a bit *too* clever!  Let me know what you think.

I realised I could implement the division operator for the Resource object, which would mean you could refer to bits of the API in a way that looked like URL paths:

    light7 = bridge / 'lights' / 7
    print light7()

You could even define `lights='lights', scenes='scenes'` etc and get rid of the quotation marks:

    light7 = bridge / lights / 7

Now, I think this is very cute, and takes precisely two lines of code to implement, but I hesitated for a couple of reasons:

First, there are already a couple of different ways to do the same thing in Qhue, and adding another may just confuse people. 

Second, you do need the words in the URL to be strings, unless they're numbers or variables, so you often need quotes, making it look a bit like a URL but not completely like a URL, which may also be confusing.

Third, if you actually want to call the API without assigning to an intermediate variable, it would be nice to do:

    light7_status = bridge / lights / 7 ()

but you can't, because the function call operator has higher precedence than division, so you have to do:

    light7_status = ( bridge / lights / 7 )()

All of which makes me think it might be a bit too clever for its own good, but I could easily put it in and leave that decision to the end user...

Any thoughts?

All the best, and thanks for your contributions!
Quentin

P.S.  Mmm...  I could even add a bit more cleverness, instead of storing the username in the Bridge object, and make that part of the path too.  So when [the official API documentation](http://www.developers.meethue.com/documentation/schedules-api-0) says:

     /api/<username>/schedules

You could actually *use* something like:

    bridge / api / myusername / schedules

I might have done that if I'd thought of it at the start...  I could probably still do it without breaking any existing code...

To:

@mozz100 @acidghost @crowsonkb @itsayellow @martin-paulus @marcusklaas 
@691175002 @SteveyO @generalelectrix

**Comment by generalelectrix** [comment]
This strikes me as bug-prone and rather non-idiomatic.

**Comment by mozz100** [comment]
It's cute, I agree - very clever idea.  On balance, I find this use of the division operator kinda weird to look at.  I'm used to seeing `.` in python.  Overall I think my suggestion would be to try to follow PEP 20 - The Zen of Python: "There should be one-- and preferably only one --obvious way to do it." - which would mean not going down this route.

**Comment by quentinsf** [comment]
Thanks all - yes, I think my misgivings when combined with yours are enough to consign this to the 'interesting but impractical ideas' bin :-)
