### ISSUE TITLE
Adressing Groups

### ISSUE THREAD

**Issue by ingm4r** [quentinsf/qhue#13]
I've tried to turn all lights on/off using the special group 0 of the bridge.
For that a PUT with a Body off

```
{ 
  "on": true
 }
```

 or 

```
{
  "on": false
 }
```

needs to be send to /api/user/groups/0/action. I've tried to do that using the following line:

   b('groups', 0, 'action', on='true', http_method='put')

which generates a PUT-Request to the URL but the body of the generated request is

```
{
  "on": "true"
 }
```

And the extra quotation marks causes an error thrown by the Hue API:

> {"error":{"type":7,"address":"/groups/0/action/on","description":"invalid value,  true }, for parameter, >on"}}]

Any ideas how that can be solved?

**Comment by quentinsf** [comment]
Hi there - well diagnosed!

I think you should find that if you use the native Python True and False values rather than strings, it'll get converted to the right thing in the request.  

i.e. try

`on=True`

instead of

`on='true'`

Does that work?

**Comment by ingm4r** [comment]
Hi,

sorry for the delay! I've switched to using python requests as a workaround. I will try your solution later one.
