### ISSUE TITLE
Use python 3 in example and readme

### ISSUE THREAD

**Issue by NicoHood** [quentinsf/qhue#18]
It would be better to use python3 examples in first place.

Also the shebang (first line of the script) should contain "python2" or "python3", so the script will work on all systems. Some older distros still use python2 as default, some dont.

**Comment by quentinsf** [comment]
Hi Nico -

Good idea about updating the examples, but most of the world does still use version 2, so I want to make sure that everything still works there.  Also, I have come across systems which don't have 'python2' or 'python3', so I think 'python' is still safer.

I've pushed a new version which makes qhue_example.py compatible with either 2 or 3, though, and the Jupyter notebook demo has been 3-compatible in the develop branch for some time - I've merged that into the main distribution in v 1.0.9.

All the best, and thanks.
