### ISSUE TITLE
GPG signatures for source validation

### ISSUE THREAD

**Issue by NicoHood** [quentinsf/qhue#19]
Hi,
I currently started using this library, as its the most flexible one while still keeping the library code size at a minimum. I've alo published a PKGBUILD for Arch Linux on AUR:
https://aur.archlinux.org/packages/python-qhue/

In order to increase the security of the qhue package, it would be nice if you can provide us with signed source tarballs. For more information and a handy automated tool you can have a look at gpgit:
 https://github.com/NicoHood/gpgit

If the AUR package becomes more popular, I am willing to move it to the official Arch Linux repository. However my personal requirement is to have GPG signatures for that to happen. Would be nice if you can have a look at it :)

**Comment by NicoHood** [comment]
Any updates on this?

**Comment by quentinsf** [comment]
Sorry for not responding,  Nico - 

GPG is one of those things I use just rarely enough -- about every 2 years or so -- to forget it between each use!  (And that's from somebody who *can* remember the openssl syntax! )  And when I do use it, it's on one of several different machines without synchronised keyrings.
So I'm always losing or forgetting past keys and replacing them with new ones for each new task, which kind of defeats the point :-)  

But I probably have some keys somewhere which haven't expired... I should try and find out!  I'll have a think about this.  I imagine 99% of people use pip to install qhue, and most of the remaining 5% will probably clone it using git, so I haven't heard of anyone using the tarballs.

However, I can see it could be useful for Arch users.  And there's the facility to incorporate signatures in the Pypi packages now, I believe, so perhaps I'll need to think about generating them soon.  

I'll try and find a key, or generate another one, and sign the latest tarballs at least!

**Comment by quentinsf** [comment]
OK - have found a key, renewed it, and signed the 1.0.12 release!

Of course, I don't think anyone's verified my key, so it tells you less than the fact that I was able to upload the files in the first place, but there is at least a signature in place!

I'll try to remember to do future releases, but do feel free to remind me if I forget.

All the best,

Quentin

**Comment by NicoHood** [comment]
Hey Quentin,
thanks for having a look at the signatures! Your key is RSA2048 which is currently sufficient long and valid until 2025 :-)

You are right, that the current way of signing the sources is not really more secure than creating a sha512sum from the github download. It would make more sense to create a tarball locally and sign this one instead of the tarball created by github.

In order to support you with this process I've written down those instructions along with a script that automates this process for every future git project, including automated github upload: https://github.com/NicoHood/gpgit
