### ISSUE TITLE
Installing qhue -- Easy if you know where to put "pip install qhue"

### ISSUE THREAD

**Issue by rick6321** [quentinsf/qhue#29]
I am new to this development environment, but have much programming experience. My environment is Visual Studio Python on Windows 10 Professional, 

I am having issues with installing your qhue API.   While your instructions indicate it  is "Easy to install, ~ pip install qhue" That to me was not very helpful.  Windows command prompt, somewhere in Visual Basic, elsewhere ( in the project would be my guess)

Sorry to sound like such a novice, but I know  I am really close, but can't find any further documentation. To assist please see the code/ errors below.

I have opened the example code, and when attempting to run, the debugger indicates the following is an error: 
  Message=No module named 'qhue'
  Source=[edited out for clarity] \Python\qhue-master\examples\qhue_example.py
  StackTrace:
  File "[edited out for clarity] \Python\qhue-master\examples\qhue_example.py", line 4, in <module>
    from qhue import Bridge, QhueException, create_new_username

To correct I simply copied the qhue into the project file, while that worked as a bandaid:
_I am willing to bet that in not recommended programming grammar! (But darn'd effective)

NOW the following code "barfed"  similar types of errors appeared for the following code (from your example) 

File "[removed for clarity] \Python\qhue-master\examples\qhue.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

 ****import requests
   import json
  # for hostname retrieval for registering with the bridge
  from socket import getfqdn
  import re
  import sys****

I thank you in advance for any help to set up the programming environment.

Gratefully,

Rick

**Comment by Tathorack** [comment]
Have a look at this if you’re using Visual Studio
https://docs.microsoft.com/en-us/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-05-installing-packages?view=vs-2019

What’s happening is that while you’ve copied the source for the qhue package to your project. This project depends on the requests module which would have been installed automatically if you installed qhue with pip. Since it’s not installed or available in your project you have an import error.

**Comment by rick6321** [comment]
Thanx for helping me resolve an issue that has nothing to do with your
package...

The lack of documentation / support for this type of issue (FROM MICROSOFT)
is appalling..

Thanx,

Rick
r <rick43056@gmail.com>ick43065@gmail.com

**Comment by quentinsf** [comment]
Thanks Rhys - I was travelling today and didn't get this until the evening, but I know almost nothing about Windows anyway!   

Yes, Rick, you want to learn how to install things with 'pip'.  As Rhys has said, `requests` would be installed automatically that way.

If you weren't installing qhue that way, but just wanted to download and run it, you'll see that like many other systems, it includes a file called 'requirements.txt', which lists the packages on which it depends.   You still need pip, but you can do `pip install -r requirements.txt` and that will install all of the things listed in the file -- here, it's just 'requests'.

All the best,
Quentin

**Comment by rick6321** [comment]
All

Thank you for the efficient, quick, and correct support, GREATLY
APPRECIATED !

Successfully installed certifi-2019.9.11 chardet-3.0.4 idna-2.8 qhue-1.0.12
requests-2.22.0 urllib3-1.25.6
----- Successfully installed 'qhue' -----

Thanx,

Rick
r <rick43056@gmail.com>ick43065@gmail.com
