### ISSUE TITLE
qhue installed but not working

### ISSUE THREAD

**Issue by kidrodi** [quentinsf/qhue#32]
When I try to run qhue from the terminal all I get is **qhue: command not found** but I know it's installed because I can run **pip3 show qhue** and its output is this: 

`Name: qhue
Version: 1.0.12
Summary: Qhue: python wrapper for Philips Hue API
Home-page: https://github.com/quentinsf/qhue
Author: Quentin Stafford-Fraser
Author-email: None
License: GNU GPL 2
Location: /usr/local/lib/python3.8/dist-packages
Requires: requests
Required-by: -mby, Amby
`

I've checked the location of the package in case it got installed in the wrong place but it doesn't seem to work no matter where I install it.

Let me know what I'm missing. Thanks.

**Comment by quentinsf** [comment]
That's because it's not a command-line utility! :-)

It's a library for writing your own code; have a look at the README.

Best,
Quentin
