### ISSUE TITLE
Changes to Whitelist username creation

### ISSUE THREAD

**Issue by SteveyO** [quentinsf/qhue#6]
Hi Quentin,

I work for Philips Hue Developer Support,  I think we have talked before.  In case you were not aware, in a few months time we will be changing the way usernames are created on the bridge (for security reasons).  Custom whitelist usernames will no longer be allowed and the bridge randomly 
generated username must be used instead.  Please see below link for more information:
http://www.developers.meethue.com/documentation/important-whitelist-changes

Judging by your readme, it looks like this issue will affect you as you are passing in a custom username when creating the bridge username.  After February 2016 this will no longer work, so it should be removed (providing you are still maintaining this project).  As shown in the above link the bridge randomly generated username (in the success response) should be used instead.  Apologies for the inconvenience.

Thanks
Steve

**Comment by quentinsf** [comment]
Steve - 

Ah - many thanks for letting me know (I’m most impressed!)

I’ll look into this.  Just got my new Bridge yesterday but haven’t had a chance to play much with it yet, beyond trying out the Siri commands on my watch :-)  Love my Hue stuff - 14 bulbs and a lightstrip so far...

All the best,
Quentin

----

Dr Quentin Stafford-Fraser
quentin@pobox.com
http://quentinsf.com
mob: +44 7798 851702
blog: statusq.org
social: @quentinsf on most services

**Comment by SteveyO** [comment]
Thanks Quentin.  Sound great, you have more Hue stuff than me : -)
I also have the new bridge but mostly an Android household so no Siri in my place which is a shame.

I will check again in a few months.  Come February 2016 I will be highlighting which Tools and SDKs work with the new username changes (http://www.developers.meethue.com/tools-and-sdks) to minimise the impact for other 3rd party devs.

Steve

**Comment by quentinsf** [comment]
Steve - 

I realised this is now sorted, and I'm just in the process of submitting a package which includes it to PyPi, so you should be able to 'pip install qhue' and get the new functionality soon.

Many thanks for your help,
Quentin
